### ISSUE TITLE
]chelp is deleted!!!! (13122021a or above versions)

### ISSUE THREAD

**Issue by archisha69** [archisha69/iso6.9-1.2beta#8]
yes i fixed ]help and ]chelp is no longer needed. However, u still have to use ]chelp in older versions as ]help is not fixed.

**Comment by notsniped** [comment]
```python
client.remove_command('help')```

**Comment by archisha69** [comment]
> ```python
> client.remove_command('help')
> 
> Then add the custom help command.
> ```python
> @client.command()
> async def help(ctx):
>    #Code here
> 
> And remove the `chelp` command.
> ```

bro ur sooooooo fkin late

**Comment by notsniped** [comment]
Yes I dont get email notifs


Im an idiot ngl

**Comment by archisha69** [comment]
do u know that i already FIXED that a century ago and this issue is closed

> Yes I dont get email notifs
> 
> Im an idiot ngl

bruh

**Comment by archisha69** [comment]
> _slowly hovers over 'close tab'_

lol
